window.TUI||(TUI={});var LaboratoryTest=function(){return window.bbsGlobal&&"797"==bbsGlobal.item?!0:!1};function intval(a){a=parseInt(a);return isNaN(a)?0:a}
function getPos(a){for(var c=0,b=0,d=intval(a.style.width),e=intval(a.style.height),g=a.offsetWidth,h=a.offsetHeight;a.offsetParent;)c+=a.offsetLeft+(a.currentStyle?intval(a.currentStyle.borderLeftWidth):0),b+=a.offsetTop+(a.currentStyle?intval(a.currentStyle.borderTopWidth):0),a=a.offsetParent;c+=a.offsetLeft+(a.currentStyle?intval(a.currentStyle.borderLeftWidth):0);b+=a.offsetTop+(a.currentStyle?intval(a.currentStyle.borderTopWidth):0);return{x:c,y:b,w:d,h:e,wb:g,hb:h}}
function getScroll(){var a,c,b,d;document.documentElement&&document.documentElement.scrollTop?(a=document.documentElement.scrollTop,c=document.documentElement.scrollLeft,b=document.documentElement.scrollWidth,d=document.documentElement.scrollHeight):document.body&&(a=document.body.scrollTop,c=document.body.scrollLeft,b=document.body.scrollWidth,d=document.body.scrollHeight);return{t:a,l:c,w:b,h:d}}
function scroller(a,c){"object"!=typeof a&&(a=document.getElementById(a||"post_head"));if(a){var b=this;b.el=a;b.p=getPos(a);b.s=getScroll();b.clear=function(){window.clearInterval(b.timer);b.timer=null};b.t=(new Date).getTime();b.step=function(){var a=(new Date).getTime(),e=(a-b.t)/c;a>=c+b.t?(b.clear(),window.setTimeout(function(){b.scroll(b.p.y,b.p.x)},13)):(a=(-Math.cos(e*Math.PI)/2+0.5)*(b.p.y-b.s.t)+b.s.t,e=(-Math.cos(e*Math.PI)/2+0.5)*(b.p.x-b.s.l)+b.s.l,b.scroll(a,e))};b.scroll=function(a,
b){window.scrollTo(b,a)};b.timer=window.setInterval(function(){b.step()},13)}}var see_only_uname=null,see_only_str=null;
function setOnlyUser(a,c){see_only_uname=a;see_only_str="#ty_vip_look["+a+"]";jQuery(".atl-pages a").attr("href");jQuery(".atl-pages a").attr("href",function(){return jQuery(this).attr("_bak")+see_only_str});a==jQuery(".see-host").attr("_uname")&&jQuery(".see-host").addClass("see-host-off");jQuery(".atl-item[_host!='"+a+"']").hide().attr("_hide","1");0==jQuery(".atl-item[_host='"+a+"']").size()?jQuery(".atl-main").prepend('<div class="bbs-info-hint">本页无楼主（或指定人）的回复，请 <a href="javascript:void(0);" class="see-all">查看本页其它回复</a></div>'):
jQuery(".bbs-info-hint").remove();toAnchor(c)}function cancelOnlyUser(a){jQuery(".see-host").removeClass("see-host-off");jQuery(".atl-item").show().removeAttr("_hide");jQuery(".bbs-info-hint").remove();see_only_str=see_only_uname=null;jQuery(".atl-pages a").attr("href",function(){return jQuery(this).attr("_bak")});toAnchor(a)}function toAnchor(a){a&&a.length&&scroller(a,100)}
function goPage(a,c,b,d){var a=a.page.value,e="";/(^-?\d\d*$)/.test(a)?(e=a>d?"post-"+c+"-"+b+"-"+d+".shtml":0>=a?"post-"+c+"-"+b+"-1.shtml":"post-"+c+"-"+b+"-"+a+".shtml",see_only_str&&(e+=see_only_str),window.location.href=e):alert("页码必须是数字！");return!1}
function replyTop(){var a=jQuery("#textAreaContainer",jQuery("#bbsPost")),c=("来吧"==bbsGlobal.blocktype&&"私密"==bbsGlobal.laibaType?"":"@")+decodeURI(jQuery(".js-bbs-act").attr("js_activityusername"));0>a.val().indexOf(c)&&a.val(function(){return c+" "+jQuery(this).val()});setTimeout(function(){TY.util.cursorPoint.toTextEnd(a.get(0))},500)}var resetDom={};
(function(a){a.extend(resetDom,{resetSeeOnly:function(){jQuery(".atl-pages a").attr("_bak",function(){return jQuery(this).attr("href")});/ty_vip_look\[(.+)\]/gi.test(window.location.hash)&&setOnlyUser(encodeURIComponent(decodeURIComponent(RegExp.$1)))},setHighlight:function(a){var b=null;keyExist=!1;if(bbsGlobal.words&&bbsGlobal.words.length)for(var d=0;d<bbsGlobal.words.length;d++)b=RegExp(bbsGlobal.words[d].word,"g"),b.test(a)&&(keyExist=!0,a=a.replace(b,'<a href="'+bbsGlobal.words[d].link+'" target="_blank" _stat=/stat/bbs/post/贴内版块>'+
bbsGlobal.words[d].word+"</a>"));return{text:a,keyExist:keyExist}},resetUserNameUtil:function(a){var b=jQuery(a).html(),b=this.setHighlight(b),d=b.text.split("@"),e=0;if(1<d.length){for(b=1;b<d.length;b++){var g=d[b].match(/^([\-\w\u4e00-\u9fa5]{1,16})/);if(g&&(g=g[1]))"."!=d[b].substring(g.length,g.length+1)&&21>e?(d[b]=d[b].replace(g,'<a href="http://www.tianya.cn/n/'+g+'" target="_blank">@'+g+"</a>"),e++):d[b]=d[b].replace(g,"@"+g)}jQuery(a).html(d.join(""))}else b.keyExist&&jQuery(a).html(d.join(""))},
resetUserName:function(){var c=this;jQuery(".atl-con-bd .bbs-content").each(function(){c.resetUserNameUtil(a(this))})},lazyLoad:function(c){var b={threshold:0,failurelimit:3,event:"scroll",effect:"show",effectspeed:500,container:window,max_width:0,elements:"img[original]"},d=function(d,b){var e;e=void 0===b.container||b.container===window?3*a(window).height()+a(window).scrollTop():a(b.container).offset().top+3*a(b.container).height();try{return e<=a(d).offset().top-b.threshold}catch(g){return!0}},
e=function(d,b){var e;e=void 0===b.container||b.container===window?a(window).scrollTop():a(b.container).offset().top;try{return e>=a(d).offset().top+b.threshold+a(d).height()}catch(g){return!1}};a.extend(a.expr[":"],{"below-the-fold":"belowthefold(a, {threshold : 0, container: window})","above-the-fold":"!belowthefold(a, {threshold : 0, container: window})"});c&&a.extend(b,c);var g=a(b.elements);if(0!=g.size()){var h=null;a(b.container).bind("scroll",function(){if(0==g.size())a(this).unbind("scroll");
else{var c=0;h&&clearTimeout(h);h=setTimeout(function(){var h=[];g.each(function(){var j=a(this);if("1"==j.closest(".atl-item").attr("_hide"))return!0;if(!e(j,b))if(d(j,b)){if(c++>b.failurelimit)return!1}else"1"!=j.attr("loaded")&&(a("<img />").one("load",function(){var d="",e="";a.browser.msie&&6==a.browser.version&&(d=this.width>b.max_width?b.max_width:this.width);a.browser.msie&&8==a.browser.version&&this.width>b.max_width&&(e=this.height*(b.max_width/this.width));j.hide().removeAttr("height").attr("src",
j.attr("original")).width(d).height(e).show();if(/http:\/\/img3.laibafile.cn\/p\/(l|m|s)\/(.+)\.(jpg|jpeg|gif|png|bmp)/gi.test(j.attr("original"))){var g=RegExp.$2;j.css({cursor:"pointer"}).bind("click",function(){var d="picall";a("#post_head .js-bbs-act").attr("js_activityusername")===a(this).closest("div.atl-item").attr("_host")&&(d="pic");window.open("http://bbs.tianya.cn/"+d+"-"+bbsGlobal.item+"-"+bbsGlobal.artId+".shtml#p="+g)})}}).one("seterrurl",function(){j.hide().removeAttr("height").attr("src",
"http://static.tianyaui.com/img/static/2011/imgloadingerr.gif").show()}).one("error",function(){a(this).trigger("seterrurl")}).attr("src",j.attr("original")),j.attr("loaded","1"),h.push(g.index(j)))});for(var k=0;k<h.length;k++)g.splice(h[k]-k,1)},200)}});a(b.container).trigger(b.event)}},bindEvent:function(){a(".see-host").bind("click",function(){see_only_uname?see_only_uname!=a(this).attr("_uname")?(a(".atl-item[_host='"+a(this).attr("_uname")+"']").show(),setOnlyUser(a(this).attr("_uname"))):cancelOnlyUser():
setOnlyUser(a(this).attr("_uname"))});a(".see-all").live("click",function(){cancelOnlyUser();a(this).closest(".bbs-info-hint").hide()})},loadApps:function(){TY.loader("TY.util.iframeResize");if(0<a("#js_survey[_id!='']").size())for(var c=a("#js_survey"),b=c.attr("_id").split(","),d=0;d<b.length;d++)c.append(['<div class="survey-view cf">','<iframe id="iframe_survey_'+b[d]+'" scrolling="no" height="0" frameborder="0" width="100%" src="http://diaocha.tianya.cn/v/open/survey/detail?surveyId='+b[d]+'&invite=0" ></iframe>',
"</div>"].join(""));if(0<a("#js_event[_id!='']").size()){c=a("#js_event");b=c.attr("_id").split(",");for(d=0;d<b.length;d++)c.append(['<div class="event-view cf">','<iframe id="iframe_event_'+b[d]+'" scrolling="no" height="0" frameborder="0" width="100%" src="http://apps.tianya.cn/event/zujian/info.php?eventid='+b[d]+"&iframeid=iframe_event_"+b[d]+'"></iframe>',"</div>"].join(""))}if(0<a("#js_album[_id!='']").size()){var e=a("#js_album"),d=e.attr("_id").split(",");a.getScript("http://apps.tianya.cn/api/album/multiGetAlbumInfo.php?var=albumList&aid="+
d.toString(),function(){var d=window.albumList;if(d&&d.result&&d.data&&d.data.infolist&&d.data.articlelist){if(0==d.data.infolist.length&&0==d.data.articlelist.length)return!1;e.append('<div class="album-view cf"></div>');var b=a(".album-view",e),c=0;a.each(d.data.articlelist,function(e){var k=[1==c%2?'<div class="album-info album-info-r">':'<div class="album-info">','<div class="hd cf">','<h3><a title="'+d.data.infolist[e].albumname+'" target="_blank" href="http://apps.tianya.cn/album/albuminfo/aid/'+
e+'">'+getStrByLen(d.data.infolist[e].albumname,50,1)+"</a></h3>",'<a href="http://apps.tianya.cn/album" target="_blank" class="to-album-page">专辑首页</a>',"</div>",'<div class="bd cf">','<div class="album-pic"><img src="'+d.data.infolist[e].imgurl+'"></div>','<div class="album-list">',"<ul>"];a.each(this,function(){k.push('<li><a target="_blank" title="'+this.articletitle+'" href="'+this.articleurl+'">'+getStrByLen(this.articletitle,36,1)+"</a></li>")});k.push("</ul>","</div>","</div>","</div>");b.append(k.join(""));
c++})}})}},init:function(){this.resetUserName();this.lazyLoad({max_width:912,elements:".atl-con-bd .bbs-content img[original]",effect:"fadeIn"});this.loadApps();this.resetSeeOnly();this.bindEvent()}})})(jQuery);
TUI.initPostView=function(a){var c={url:"http://click.tianyaui.com/qce.jsp?error={errorTxt}&_r={_r}",timer:null,start:0,xhr:null,duration:5E3,Constant:{descMax:500,Fail:"F",Success:"S",Post:"P",Reply:"R",ServerResponse:"serverResponse"},setXHR:function(a){this.xhr=a},active:function(){var a=this;this.timer||(this.timer=setTimeout(function(){a.clear({readyState:a.xhr?a.xhr.readyState:"",status:a.xhr&&a.xhr.status?a.xhr.status:"",code:"noResponse",desc:"超时30s无响应"})},6*this.duration),this.start=(new Date).getTime())},
clear:function(a){if(this.timer){clearTimeout(this.timer);this.xhr=this.timer=null;var b=(new Date).getTime()-this.start,c=parseInt(b/this.duration,10),c={op:this.Constant.Reply,success:this.Constant.Fail,time:b,timeInterval:"("+5*c+"s,"+(5*c+5)+"s)",code:"",desc:"",user:__global.getUserName()||""};if(!0===a){if(b<this.duration)return;c.success=this.Constant.Success;c.readyState=4;c.status=200;c.code="success";c.desc="响应时间大于5s"}else{c.readyState=a.readyState;c.status=a.status;c.code=a.code;c.desc=
a.desc;c.code||(c.code="error");if(!c.desc||"null"===c.desc||"Unknown"===c.desc||"parsererror"===c.code)c.desc=a.responseText||"未知错误：responseText为空";c.desc=c.desc.substr(0,this.Constant.descMax)}this.sendError(TY.util.json(c))}},createImg:function(){var a=document.createElement("img");a.id="stat_img"+(new Date).getTime();a.style.display="none";document.body.appendChild(a);this.imgEl=document.getElementById(a.id)},sendError:function(a){this.imgEl||this.createImg();this.imgEl.src=this.url.replace(/\{errorTxt\}/,
encodeURIComponent(a)).replace(/\{_r\}/,Math.random())}},b={};a.extend(b,{replayUrl:"/api?method=bbs.ice.reply",twitterUrl:"http://www.tianya.cn/api/tw?method=tweet.ice.shareTweet",editor:null,isAuth:!1,popCon:null,authInfo:{},getReplyAreaContent:function(a){var b=jQuery,c=a.closest(".atl-item"),h=c.find(".atl-info .js-vip-check").text(),f="";c.find(".atl-info span").each(function(){var a=b(this).text();-1!==a.indexOf("时间：")&&(f=a.replace("时间：",""))});a=a.attr("floor");this.drawReplay(h,f,c.find(".bbs-content"),
+a)},drawReplay:function(d,b,c,h){var f=c.contents(),i=[],c=[],k="",j=[];h&&(k=h+"楼 ");f.each(function(){var d="";"string"===typeof this?(d=a.trim(this))&&i.push("    "+d):"BR"===a(this).prop("tagName")||"STYLE"===a(this).prop("tagName")?i.push("\n"):"IMG"===a(this).prop("tagName")?i.push("\n    "+a(this).attr("src")+"\n"):(d=a.trim(a(this).text()))&&i.push("    "+d)});j=i.join("").match(/(.|\n)*\-{15,}/g);c.push(j?j+"\n":"");c.push("    "+("来吧"==bbsGlobal.blocktype&&"私密"==bbsGlobal.laibaType?"":
"@")+d+" "+k+b+"\n");d=i.join("").replace(/(.|\n)*\-{15,}/g,"");b=function(d,b){var e=d.match(/https?:\/\/[a-zA-Z0-9]+(\.[a-zA-Z0-9]+)+([-_A-Z0-9a-z\$\.\+\!\*\/,:;@&=\?\~\#\%]*)*/gi)||[],c=!0;a.each(e,function(a,e){for(var g=d.split(e),f=0,h=e.getCNlen(),j="",i=0;i<g.length;i++){f+=g[i].getCNlen();j+=g[i];j+=e;if(f<b&&f+h>b)return d=j+"......",c=!1,!0;f+=h}});c&&(d=d.subStringCn(b,!0)+"....");return d};400<d.getCNlen()&&(d=b(d,400));c.push(d);c.push("\n    -----------------------------\n");var c=
c.join(""),c=c.replace(/\n+/g,"\n"),l=a("#textAreaContainer",a("#bbsPost"));l.val(c);setTimeout(function(){TY.util.cursorPoint.toTextEnd(l.get(0))},500)},insertHtml:function(d,b){var c=__global.getUserId(),h=bbsGlobal.trueName||__global.getUserName(),f=[];f.push('<div class="atl-item" _host="'+c+'">');f.push('\t<div class="atl-head">');f.push('\t\t<div class="atl-head-reply">');f.push('\t\t\t<a href="#fabu_anchor" class="a-link reply">回复</a>末楼');f.push("\t\t</div>");f.push('\t<div class="atl-info">');
f.push('\t\t<span>作者：<a class="js-vip-check" href="http://www.tianya.cn/'+c+'" target="_blank">'+h+"</a> </span>");b&&(b=b.replace(/\..*/g,""),f.push("\t\t<span>时间："+b+" </span>"));f.push("\t</div>");f.push("</div>");f.push('<div class="atl-content">');f.push('\t<div class="atl-con-hd clearfix">');f.push('\t\t<div class="atl-con-hd-l"></div>');f.push('\t\t<div class="atl-con-hd-r"></div>');f.push("\t</div>");f.push('\t<div class="atl-con-bd clearfix">');f.push('       <div class="bbs-content">');
f.push(d);f.push("       </div>");f.push("\t</div>");f.push('\t\t<div class="atl-con-ft clearfix">');f.push('\t\t<div class="atl-con-ft-l"></div>');f.push('\t\t<div class="atl-con-ft-r"></div>');f.push("\t</div>");f.push("</div>");f.push("</div>");a(".atl-main").append(f.join(""));resetDom.resetUserNameUtil(a(".atl-main").find(".bbs-content:last"))},bindEvent:function(){var d=this;a("a.reply").bind("click",function(){d.getReplyAreaContent(a(this))});a(".replytop").bind("click",replyTop);a(".common-submitBtn",
a(".post-div")).click(function(){a(this).prop("disabled")?new TY.ui.tips({msg:"大侠，你的动作太快了，不如休息下吧。",position:"midCenter",time:2500,type:"warn"}):(a(this).attr("disabled","disabled"),__global.isOnline()||LaboratoryTest()?d.submitAction():TY.loginAction())});a("#textAreaContainer",a(".post-div")).keypress(function(d){(10===d.which||13===d.which&&!0===d.ctrlKey)&&a(".common-submitBtn",a(".post-div")).click()});a(".common-submitBtn").attr("title","Ctrl+Enter快捷发表");a("#isTwitter").change(function(){TY.io.storage.set("bbsReplyTwitter",
a(this).prop("checked"))});a("#codeImg").live("click",function(){d.oCode()})},oCode:function(){var a="http://imgcode.tianya.cn/services/ImageCodeService?_r="+(new Date).getTime();jQuery("#imgCode").attr("src",a);jQuery("#validateCode").attr("value","")},codeWin:function(){var d=this;d.popCon=new TY.ui.pop({headTxt:"请输入验证码",body:"<div class='fb_yzm_main'><div class='fb_yzm_main_col'><p><label for='validateCode'>验证码：</label><input type='text' size='20' id='validateCode' name='validateCode'/></p></div><div class='fb_yzm_main_col2'> <img id='imgCode' /> <a id='codeImg' href='javascript:void(0);'>看不清，换一个</a><input type='hidden' name='vk_code' id='vk_code' size='12' /></div><div class='fb_yzm_main_col3'></div></div>",
type:"window",isDrag:!0,Buttons:[{id:"Button1",text:"确定",handler:function(){b.codeCheck()}},{id:"Button2",text:"取消",handler:function(){d.popCon.remove()}}]});d.oCode();a(".common-submitBtn",a(".post-div")).removeAttr("disabled")},codeCheck:function(){__global.getCookie("vk");var a=jQuery("input[id=validateCode]");""==a.val()?alert("请输入验证码"):(this.popCon.remove(),this.submitAction(a.val()))},picCheck:function(a){if(a){for(var a=a.match(/https?:\/\/[a-zA-Z0-9]+(\.[a-zA-Z0-9]+)+([-_A-Z0-9a-z\$\.\+\!\*\/,:;@&=\?\~\#\%]*)*/gi)||
[],b=0;b<a.length;b++)if(/\.(jpg|jpeg|gif|png|bmp)$/.test(a[b])&&!/^http:\/\/[a-zA-Z0-9]+(\.[a-zA-Z0-9]+)*\.(laibafile.cn|tianya.cn|tianyaui.com|tianyablog.com)\//.test(a[b]))return!0;return!1}},validate:function(){var d=a("#textAreaContainer").val(),b={checked:!0};if(1>d.trim().length)return b.checked=!1,this._showTips("回复不能为空","warn"),b;if(8E3<d.getCNlen())return b.checked=!1,this._showTips("帖子内容太长（4000个汉字以内）","warn"),b;if(this.picCheck(d))return b.checked=!1,new TY.ui.pop({headTxt:"提示",type:"confirm",
body:'<p class="mb5">抱歉╮(╯﹏╰）╭，站外图片不允许直接发表，请按下图所示步骤操作</p><div><img style="display:block;" width="544" height="239" src="http://static.tianyaui.com/global/lite/images/bbs-post-pic-warn.png" /></div>'}),a(".common-submitBtn",a(".post-div")).removeAttr("disabled"),b;b.checked&&(b.item="",b.content=BBS_UTIL.valueHandler(d),b.unValue=d);return b},submitAction:function(b){var e=this,g=this.validate(),h;if(g.checked){e.popItem=new TY.ui.tips({el:a("#textAreaContainer"),type:"loading",msg:"操作中...",position:"midCenter"});
h={"params.artId":TY.param.getParam("id")||bbsGlobal.artId,"params.item":TY.param.getParam("item")||bbsGlobal.item,"params.appId":jQuery("#post_head .atl-menu").attr("js_appid"),"params.appBlock":TY.param.getParam("item")||bbsGlobal.item,"params.postId":TY.param.getParam("id")||bbsGlobal.artId,"params.preUrl":jQuery("#post_head .atl-menu").attr("js_activityurl"),"params.preTitle":decodeURI(jQuery("#post_head .atl-menu").attr("js_title")),"params.preUserId":jQuery("#post_head .atl-menu").attr("_host"),
"params.preUserName":decodeURI(jQuery("#post_head .atl-menu").attr("js_activityusername")),"params.prePostTime":jQuery("#post_head .atl-menu").attr("js_posttime"),"params.sourceName":"天涯论坛","params.type":3,"params.bScore":!0,"params.content":g.content,"params.title":g.content,"params.bWeiBo":!1};b&&(h["params.vCode"]=b);c.active();var f=a.ajax({url:e.replayUrl,headers:{Connection:"close"},dataType:"json",type:"post",data:h,success:function(b){e.popItem.remove();1==b.success?(c.clear(!0),"false"==
b.data.success&&/验证码/.test(b.data.message)?(/验证码\[\]/.test(b.data.message)||alert("验证码错误，请重新输入。"),e.codeWin()):b.data.error_code&&-111==b.data.error_code?TUI.laibaJoinPop({titleInfo:"本版只允许版块成员才能发帖，您可以申请加入",closeFn:function(){a(".common-submitBtn",a(".post-div")).removeAttr("disabled")}}):(e._showTips("回复成功","success"),e.insertHtml(b.data&&b.data.content||"",b.data&&b.data.time),a("#textAreaContainer").val(""),a("#isTwitter").prop("checked")&&new TY.util.proxy({name:"tianyacnProxy",path:"http://www.tianya.cn/proxy.html"},
"ajax",{url:"http://www.tianya.cn/api/tw?method=tweet.ice.shareTweet",data:h,type:"post",dataType:"json",success:function(a){1==+a.success?TY.util.console({title:"转发微博成功",msg:a.message}):TY.util.console({title:"转发微博失败",msg:a.message})}}))):(new TY.ui.pop({body:b.message}),setTimeout(function(){a(".common-submitBtn",a(".post-div")).removeAttr("disabled")},5E3),c.clear({code:c.Constant.ServerResponse,desc:b.message,readyState:f&&f.readyState||0,status:f&&f.status||""}))},error:function(b,d,g){c.clear({readyState:b.readyState,
status:b.status,code:d,desc:g,responseText:b.responseText});e.popItem.remove();setTimeout(function(){a(".common-submitBtn",a(".post-div")).removeAttr("disabled")},5E3)}});c.setXHR(f)}},checkStorage:function(){var b=TY.io.storage.get("bbsReplyTwitter");b&&("true"==b?a("#isTwitter").attr("checked",!0):a("#isTwitter").attr("checked",!1))},getRealUser:function(b){var c=this;a.ajax({url:"/api?method=bbs.api.vip&params.userIds="+__global.getUserId(),dataType:"json",cache:!1,success:function(a){1===+a.success?
(a=a.data,"undefined"!=typeof a.rows&&0<a.rows.length&&(c.isAuth=!0,c.authInfo=a.rows[0]),b&&b()):new TY.ui.tips({type:"warn",msg:a.message||"获取认证信息错误",position:"midCenter",time:2500})},error:function(){TY.util.console("getRealUser error")}})},init:function(){var b=this;if(0<a("#bbsPost").size()){a("#textAreaContainer").width(630);if(!__global.isOnline()){var c=("btn"+Math.random()).replace(".",""),g='<div class="bbsPostLogin"><a href="javascript:void(0);" id="'+c+'">登录</a> | <a href="http://passport.tianya.cn/register/default.jsp?sourceURL='+
encodeURIComponent(window.location)+'">注册</a>';LaboratoryTest()&&(g+='<span class="guest-reply-tip">亲，您没账号也可以在天涯试验场直接发帖提交建议的哦</span>');jQuery("#bbsPost").before(g+"</div>");jQuery("#"+c).bind("click",function(){TY.loginAction()})}this.checkStorage();if("undefined"!=typeof bbsGlobal.itemPermission){if(4==bbsGlobal.itemPermission&&!__global.isOnline()){TY.loginAction(!1);return}if(5==bbsGlobal.itemPermission){if(!__global.isOnline())return;this.getRealUser(function(){b.isAuth||a(".post-div").empty().addClass("bbs-info-hint").html('<a href="#" class="a-anchor" name="fabu_anchor"></a>本版需要<a href="http://www.tianya.cn/mobile/identity" target="_blank">认证</a>后回复')})}}TY.loader("TY.ui.bbsPost",
function(){var b="friend,photo";!__global.isOnline()&&LaboratoryTest()&&(b="",jQuery("#isTwitter").closest("label").remove());window.bbsContent=new TY.ui.bbsPost({BBSObj:"bbsContent",el:a("#bbsPost"),toolWrap:a("#editorToolBar"),plugins:b})});this.bindEvent()}else a(".post-div").empty().addClass("bbs-info-hint").html('<a href="#" class="a-anchor" name="fabu_anchor"></a>本帖已不能回复')},_showTips:function(b,c){"undefined"==typeof TY.ui.tips?TY.loader("TY.ui.tips",function(){setTimeout(function(){new TY.ui.tips({el:a("#bbsPost"),
type:c||"success",msg:b||"发布成功",position:"midCenter",time:3E3,callback:function(){a(".common-submitBtn",a(".post-div")).removeAttr("disabled")}})},100)}):new TY.ui.tips({el:a("#bbsPost"),type:c||"success",msg:b||"发布成功",position:"midCenter",time:3E3,callback:function(){a(".common-submitBtn",a(".post-div")).removeAttr("disabled")}})}});b.init()};
TUI.formatBbsMusic=function(a){var c={"default":{playerUrl:"http://static.tianyaui.com/global/ty/resources/swf/iMusicA.swf",width:403,height:60},imusica:{playerUrl:"http://static.tianyaui.com/global/ty/resources/swf/iMusicA.swf",width:403,height:60},imusica2:{playerUrl:"http://static.tianyaui.com/global/ty/resources/swf/iMusicA.swf",width:403,height:60}},b=function(a,b){var c=a.match(RegExp("\\?(?:.+&)?"+b+"=(.*?)(?:&.*)?$"));return c?c[1]:""};a('span[name="music_player"]').each(function(){var d=
a.trim(a(this).attr("value"));if(""!=d){var e="",g="",h="",f="",e=d.split(","),g=d="";1===e.length?(g="imusica2",-1!==e[0].indexOf("iMusicA2")?(f=a.param({musicId:b(e[0],"musicId"),username:b(e[0],"username")}),b(e[0],"autoStart"),d="&"+a.param({albumId:"",albumname:""})):f="username=天涯音乐&musicId=0&targetUrl="+e[0]):(g=e[0],f=a.param({musicId:e[3],username:e[4]}),d="&"+a.param({albumId:e[1],albumname:e[2]}));if(h=c[g]){var e=h.width,g=h.height,h=h.playerUrl,i='<object classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" ,id="${application}" width="${width}" height="${height}" ,codebase=" http://fpdownload.macromedia.com/get/flashplayer/current/swflash.cab">,<param name="movie" value="${swf}" />,<param name="quality" value="high" />,<param name="bgcolor" value="${bgcolor}" />,<param name="wmode" value="transparent" />,<param name="allowScriptAccess" value="always" />,<param name="FlashVars" value="${flashvars}" />,<embed src="${swf}" quality="high" bgcolor="${bgcolor} ",width="${width}" height="${height}" name="${application}" align="middle" ,play="true" ,loop="false" ,wmode="transparent" ,quality="high" ,flashvars="${flashvars}",allowScriptAccess="always" ,type="application/x-shockwave-flash" ,pluginspage=" http://www.adobe.com/go/getflashplayer">,</embed>,</object>'.split(","),
f=function(b){var d=i.join("");a.each(b,function(a,b){d=d.replace(RegExp("\\$\\{"+a+"\\}","g"),b)});return d}({bgcolor:"",application:"iMusicPlayer",width:e,height:g,swf:h,flashvars:f+"&autoStart=false"+d});a(this).html(f).css({margin:"10px 0","text-align":"center",display:"block"})}}})};
function bindSelPosition(a){function c(){d.box.hide();b=!1}var b=!1,d={parent:null,box:null,top:0,left:0,directionLeft:0};jQuery.extend(d,a||{});d.parent.bind("mouseenter",function(){if(b)clearTimeout(b);else{var a=0,c=0,a=d.parent.offset().top+d.parent.height()+d.top,c=d.directionLeft?d.parent.offset().left+d.parent.outerWidth()-d.box.outerWidth():d.parent.offset().left+d.left;d.box.css({top:a,left:c});d.box.show()}}).bind("mouseleave",function(){b=setTimeout(c,100)});d.box.bind("mouseenter",function(){b&&
clearTimeout(b)}).bind("mouseleave",function(){b=setTimeout(c,100)})}
TUI.initTopMore=function(a){var c=a("a.acl-more");({init:function(){c.size()&&(a("body").append('<div id="f_moreBox"><ul class="f-morebox" class="clearfix"><li><a href="javascript:void(0);" class="icos icos-3 js-album">加入专辑</a></li><li><a href="javascript:void(0);" class="icos icos-5 js-gift">赠送礼物</a></li></ul></div>'),bindSelPosition({parent:c,box:a("#f_moreBox"),top:2,left:-35}));a("a.acl-more").show();this.bindEvent()},bindEvent:function(){a("a.js-album").attr("target","_blank").attr("href","http://apps.tianya.cn/my_album_titlelist?fromurl="+
encodeURIComponent(window.location));a("a.js-gift").bind("click",function(){if(__global._isOnline){var b=new TY.ui.pop({headTxt:"赠送礼物",body:'<iframe frameborder="0" scrolling="no" id="app_gift" name="app_gift" src="http://apps.tianya.cn/gift/presentselect.php?sendnames='+encodeURIComponent("@"+decodeURIComponent(a(".js-bbs-act").attr("js_activityusername")))+"&itemid="+bbsGlobal.item+"&articleid="+bbsGlobal.artId+'"></iframe>',isMod:!0,isShowButton:!1});window.objReSize||(window.giftReSize=function(d,
c){a("#app_gift").css({width:d,height:c});b.popPosHandler()});window.closeGiftWindow||(window.closeGiftWindow=function(){b.remove()})}else TY.loginAction()})}}).init()};
TUI.initShareBox=function(a){var c=a("#shareBox"),b=a("a.acl-share");({shareData:{site:encodeURIComponent("天涯社区"),title:"",title_gbk:"",url:""},getPageData:function(){var b=a(".js-bbs-act");with(this.shareData)title=b.attr("js_title"),title_gbk=b.attr("js_title_gbk"),url=b.attr("js_activityurl")+"?event=share|share-"},bindEvent:function(){var b=this;a(".js-tyweibo").bind("click",function(){if(__global.isOnline()){var b=a(".js-bbs-act"),d=decodeURIComponent;b.attr("js_activityuserid");b.attr("js_appid");
d(b.attr("js_title")||"");d(b.attr("js_activityusername"));d(b.attr("js_activityurl"));b.attr("js_posttime");var c=TUI.getRandom("bbs_share_t");new TY.ui.pop({headTxt:"转发并回复",body:'<div id="'+c+'" style="width:600px;height:166px;">正在加载...</div>',isMod:!0,isShowButton:!1});(function(){a("#"+c).html("");TY.loader("TY.ui.twitterPost",function(){window.twitterPost=new TY.ui.twitterPost({el:a("#"+c),isCross:!0,type:"shareTweet",oPostData:{artId:TY.param.getParam("id")||bbsGlobal.artId,item:TY.param.getParam("item")||
bbsGlobal.item,appId:jQuery("#post_head .atl-menu").attr("js_appid"),appBlock:TY.param.getParam("item")||bbsGlobal.item,postId:TY.param.getParam("id")||bbsGlobal.artId,preUrl:jQuery("#post_head .atl-menu").attr("js_activityurl"),preTitle:decodeURI(jQuery("#post_head .atl-menu").attr("js_title")),preUserId:jQuery("#post_head .atl-menu").attr("_host"),preUserName:decodeURI(jQuery("#post_head .atl-menu").attr("js_activityusername")),prePostTime:jQuery("#post_head .atl-menu").attr("js_posttime"),sourceName:"天涯论坛",
type:3,bScore:!0,"params.bWeiBo":!1},callback:function(){},plugins:"friend,emotion",twitterObj:"twitterPost"})})})()}else TY.loginAction()});a(".js-sinaweibo").bind("click",function(){window.open("http://service.weibo.com/share/share.php?url="+encodeURIComponent(b.shareData.url+"sina-weibo")+"&title="+b.shareData.title+"&content=utf-8&ralateUid=2140585607&appkey=482040646","sw","toolbar=0,status=0,resizable=1,width=440,height=430")});a(".js-qzone").bind("click",function(){window.open("http://sns.qzone.qq.com/cgi-bin/qzshare/cgi_qzshare_onekey?url="+
encodeURIComponent(b.shareData.url+"q-zone")+"&title="+b.shareData.title+"&site="+b.shareData.site,"qw","toolbar=0,status=0,resizable=1,width=600,height=480")});a(".js-qqweibo").bind("click",function(){window.open("http://share.v.t.qq.com/index.php?c=share&a=index&url="+encodeURIComponent(b.shareData.url+"qq-weibo")+"&assname="+b.shareData.site+"&title="+b.shareData.title,"qw2","toolbar=0,status=0,resizable=1,width=600,height=480")});a(".js-renren").bind("click",function(){window.open("http://share.xiaonei.com/share/buttonshare.do?link="+
encodeURIComponent(b.shareData.url+"renren")+"&title="+b.shareData.title,"rw","toolbar=0,status=0,resizable=1,width=600,height=400")});a(".js-tieba").bind("click",function(){window.open("http://tieba.baidu.com/f/commit/share/openShareApi?url="+encodeURIComponent(b.shareData.url+"tieba")+"&title="+b.shareData.title_gbk,"tw","toolbar=0,status=0,resizable=1,width=600,height=400")});a(".js-douban").bind("click",function(){window.open("http://www.douban.com/recommend/?url="+encodeURIComponent(b.shareData.url+
"douban")+"&title="+b.shareData.title,"dw","toolbar=0,resizable=1,scrollbars=yes,status=1,width=600,height=400")});a(".js-penyou").bind("click",function(){window.open("http://sns.qzone.qq.com/cgi-bin/qzshare/cgi_qzshare_onekey?to=pengyou&url="+encodeURIComponent(b.shareData.url+"penyou")+"&title="+b.shareData.title+"&site="+b.shareData.site,"qw","toolbar=0,status=0,resizable=1,width=600,height=480")})},init:function(){c.size()&&c.html('<a href="javascript:void(0);" class="share-icos share-icos-1 js-tyweibo" title="分享到天涯微博">天涯微博</a><a href="javascript:void(0);" class="share-icos share-icos-2 js-sinaweibo" title="分享到新浪微博"></a><a href="javascript:void(0);" class="share-icos share-icos-4 js-qqweibo" title="分享到腾讯微博"></a><a href="javascript:void(0);" class="share-icos share-icos-3 js-qzone" title="分享到QQ空间"></a><a href="javascript:void(0);" class="share-icos share-icos-5 js-renren" title="分享到人人网"></a><a href="javascript:void(0);" class="share-icos share-icos-6 js-tieba" title="分享到百度贴吧"></a><a href="javascript:void(0);" class="share-icos share-icos-7 js-douban" title="分享到豆辨网"></a><a href="javascript:void(0);" class="share-icos share-icos-8 js-penyou" title="分享到腾讯朋友"></a>');
b.size()&&(a("body").append('<div id="f_shareBox" _stat="/stat/bbs/post/分享"><ul class="f-selbox" class="clearfix"><li><a href="javascript:void(0);" class="share-icos share-icos-2 js-sinaweibo">新浪微博</a></li><li><a href="javascript:void(0);" class="share-icos share-icos-4 js-qqweibo">腾讯微博</a></li><li><a href="javascript:void(0);" class="share-icos share-icos-3 js-qzone">QQ空间</a></li><li><a href="javascript:void(0);" class="share-icos share-icos-5 js-renren">人人网</a></li><li><a href="javascript:void(0);" class="share-icos share-icos-6 js-tieba">百度贴吧</a></li><li><a href="javascript:void(0);" class="share-icos share-icos-7 js-douban">豆辨网</a></li><li><a href="javascript:void(0);" class="share-icos share-icos-8 js-penyou">腾讯朋友</a></li><li><a href="javascript:void(0);" class="share-icos share-icos-1 js-tyweibo">天涯微博</a></li></ul></div>'),
bindSelPosition({parent:b,box:a("#f_shareBox"),top:2,left:-36}));this.getPageData();this.bindEvent()}}).init()};
TUI.relevantAct_web=function(a){({keyWords:"",keyForGbk:"0",initDom:function(){a(".atl-main .atl-item").first().after('<div id="relevant_rom_all_w" class="relevant-article mt10 clearfix" style="display:none"><div id="relevant_rom_all" class="fl clearfix" _stat="/stat/bbs/post/相关阅读"><h3>相关阅读</h3><div class="relevant-key"></div><ul class="text-list"></ul></div></div>')},getWords:function(){function a(b,d){for(var c=d.toString(1).split("&"),f=-1,i="",k=[],j=0;j<c.length;j++)f=c[j].indexOf("="),-1!=f&&
(i=c[j].substring(0,f),k[i]=c[j].substring(f+1));return k[b]}var b=document.referrer,d=b.substring(b.indexOf("?")+1,b.length);if(/^http:\/\/www.baidu.com\/(s|baidu)\?.*/g.test(b)){if(/ie=utf-8/g.test(d))return TY.param.getParam("wd",d)?TY.param.getParam("wd",d):TY.param.getParam("word",d);this.keyForGbk="1";return a("wd",d)}if(/^http:\/\/www.google.com.hk\/search\?.*/g.test(b))return TY.param.getParam("q",d);if(/^http:\/\/www.sogou.com\/web\?.*/g.test(b))return this.keyForGbk="1",a("query",d);if(/^http:\/\/www.so.com\/s\?.*/g.test(b)||
/^http:\/\/so.360.cn\/s\?.*/g.test(b))return TY.param.getParam("q",d);if(/^http:\/\/www.soso.com\/q\?.*/g.test(b))return this.keyForGbk="1",a("w",d)},getActList:function(){a.ajax({url:"http://search.tianya.cn/fcgi-bin/tj",dataType:"script",type:"get",scriptCharset:"gbk",data:{pos:6,url:document.location.href,relay:this.keyWords,lw:+this.keyForGbk?"gbk":"utf8",title:decodeURIComponent(a(".js-bbs-act").attr("js_title")),l:"utf8"},success:function(){for(var c=window.tuijian_bbs_web,b=c.rel_words.split(" "),
d=["关键词："],e=0;e<b.length;e++)d.push('<a href="http://bbs.tianya.cn/tag/'+encodeURIComponent(b[e])+'" target="_blank">'+b[e]+"</a>&nbsp;");a("#relevant_rom_all_w .relevant-key").html(d.join(""));b=[];for(e=0;e<c.res.length&&8>e;e++)d=c.res[e],b.push('<li><a title="'+d.title+'" target="_blank" href="'+d.url+'">'+d.title+"</a></li>");a("#relevant_rom_all_w ul.text-list").html(b.join(""));a("#relevant_rom_all_w").show()}})},checkUrl:function(){return/^(http|https):\/\/.*\.(tianya\.cn|hainan\.net)\/.*/g.test(document.referrer)},
init:function(){"1"==window.bbsGlobal.page&&!__global.isOnline()&&!this.checkUrl()&&(this.initDom(),this.keyWords=this.getWords(),this.getActList())}}).init()};
TUI.relevantAct=function(){var a=jQuery,c=a("#relevant_article");({insetHtml:function(a){for(var d="",e=0;e<a.length&&10>e;e++)d+='<li><a href="'+a[e].url+'" target="_blank" title='+a[e].title+">"+getStrByLen(a[e].title,60,1)+"</a></li>";c.prepend('<div id="relevant_rom" class="fl clearfix"><h3>相关推荐</h3><ul class="text-list" _stat="/stat/bbs/post/相关推荐"></ul></div>');c.find("#relevant_rom ul.text-list").html(d);c.show()},init:function(){var b=this;a.ajax({url:"http://search.tianya.cn/fcgi-bin/tj",
dataType:"script",type:"get",scriptCharset:"gbk",data:{pos:4,url:document.location.href,title:decodeURIComponent(a(".js-bbs-act").attr("js_title")),l:"utf8"},success:function(){var d=window.tuijian_bbs;d&&0<d.length&&(8>d.length?a.ajax({url:"http://search.tianya.cn/fcgi-bin/tj",dataType:"script",type:"get",scriptCharset:"gbk",data:{pos:6,url:document.location.href,title:decodeURIComponent(a(".js-bbs-act").attr("js_title")),l:"utf8"},success:function(){d=d.concat(window.tuijian_bbs_web.res);b.insetHtml(d)}}):
b.insetHtml(d))}})}}).init()};
TUI.initReport=function(a){var c=function(b,c){var g=a("#"+c),h=g.find("input[name='reason']:checked").val();if("其它"==h){g=g.find(".int_textarea").val();if(""==g||"我对这个有意见"==g)return new TY.ui.tips({type:"warn",msg:"请填写好举报理由",position:"midCenter",time:1500}),!1;h=g}0==a(b).closest(".atl-item").size()?jQuery.trim(a(".atl-item:first").find(".bbs-content").html()):jQuery.trim(a(b).closest(".atl-item").find(".bbs-content").html());g={item:bbsGlobal.item,artId:bbsGlobal.artId,replyId:a(b).attr("replyid"),
authorId:a(b).attr("authorId"),author:a(b).attr("author"),authorTime:a(b).attr("replytime"),reason:h,reporter:__global.getUserName(),page:bbsGlobal.page,floor:a(b).closest(".atl-item").attr("id")||0};a.ajax({type:"Post",cache:!1,timeout:2E3,data:a.param(g),url:"/ty_report.jsp",complete:function(){new TY.ui.tips({msg:"举报成功，非常感谢您对天涯社区的支持！",position:"midCenter",time:2500})}});return!0},b=__global.getCookie("right");__global.isOnline()&&/^web4=y/.test(b)?a("a.reportme").css({visibility:"visible"}):(a(".atl-item").hover(function(){var b=
a(this).find("a.reportme");b.size()?b.css({visibility:"visible"}):a("#post_head a.reportme").css({visibility:"visible"})},function(){var b=a(this).find("a.reportme");b.size()?b.css({visibility:"hidden"}):a("#post_head a.reportme").css({visibility:"hidden"})}),a("#post_head .atl-head-reply").hover(function(){a(this).find("a.reportme").css({visibility:"visible"})},function(){a(this).find("a.reportme").css({visibility:"hidden"})}));a("a.reportme").bind("click",function(){if(__global.isOnline()){var b=
"report_"+Math.floor(1E4*Math.random()),e='<div id="{reportViewID}" class="report-view"><dl><dt>请选择举报类型</dt><dd>举报对象：<a href="http://www.tianya.cn/n/{author}" target="_blank">{author}</a></dd><dd>举报原因：<label><input name="reason" type="radio" value="广告" checked="checked" />广告</label><label><input name="reason" type="radio" value="谩骂" />谩骂</label><label><input name="reason" type="radio" value="色情" />色情</label><label><input name="reason" type="radio" value="违法" />违法</label><label><input name="reason" type="radio" value="其它" />其它</label></dd><dd id="input_reason">举报内容：<textarea name="report_reason" rows="3" class="int_textarea">我对这个有意见</textarea></dd></dl></div>'.replace(/\{reportViewID\}/g,
b),e=e.replace(/\{author\}/g,a(this).attr("author")),g=this,h=new TY.ui.pop({headTxt:"举报：",body:e,type:"window",isDrag:!1,Buttons:[{id:"submitBtn",text:"确定",handler:function(){c(g,b)&&h.remove()}},{id:"operation1",text:"取消",handler:function(){i();h.remove()}}],closeHandler:function(){i()}}),f=a("#"+b);f.find(".int_textarea").bind("focus",function(){this.value=""});f.find("input[name='reason']").bind("change",function(){"其它"==a(this).val()?f.find("#input_reason").show():f.find("#input_reason").hide()});
var i=function(){f.find("input[name='reason']").unbind("change");f.find(".int_textarea").unbind("focus")}}else TY.loginAction()})};TUI.initAdmin=function(){__global.isOnline()&&/^web4=y/.test(__global.getCookie("right"))&&In.load(TY_lite_url+"/js/bbs/admin.js?v=20131105","js")};
TUI.initMark=function(a){var c=function(b,c){__global.isOnline()?setTimeout(function(){a.ajax({url:iceURL,dataType:"script",type:"get",data:c,success:function(){var a=window[c["var"]];a&&a.success?new TY.ui.tips({msg:b+'成功，<a href="http://bbs.tianya.cn/my_collect.jsp" target="_blank">查看我的收藏</a>',position:"midCenter",time:2500}):new TY.ui.tips({type:"warn",msg:a.message||b+"失败",position:"midCenter",time:2500})}})},0):TY.loginAction()};(function(){var b=a(".js-bbs-act"),d={"var":"add_mark",method:"bbsArticleMark.insert",
"params.blockId":bbsGlobal.item,"params.articleId":bbsGlobal.artId,"params.title":decodeURI(b.attr("js_title")),"params.authorId":b.attr("js_activityuserid"),"params.authorName":decodeURI(b.attr("js_activityusername")),"params.markResId":0,"params.markFloorId":0,"params.grade":b.attr("js_grade")};("主版"!=bbsGlobal.itemType||bbsGlobal.isNewArticle)&&a("a.mark").bind("click",function(){var b=a(this).closest(".atl-item");a.extend(d,{"params.markResId":b.attr("replyid"),"params.markFloorId":b.attr("id")});
c("收藏",d)});a("a.marktop").bind("click",function(){var b=a(".js-bbs-act");a.extend(d,{"params.markResId":b.attr("js_postid"),"params.markFloorId":0});c("收藏",d)})})()};
TUI.initBrand=function(a){var c=jQuery,b=decodeURIComponent(c(".js-bbs-act").attr("js_title"));c.ajax({url:"http://803.tianya.cn/keyword",dataType:"script",type:"get",scriptCharset:"gbk",data:{varPara:"adsObj",handle:"json",returnNum:6,title:b},success:function(){var b=[],c=window.adsObj;c&&c.ads&&c.ads.length&&(jQuery.each(c.ads,function(a,c){b.push("<li><span>.</span>");b.push('<a target="_blank" href="'+c.ads_url+'">'+c.ads_title+"</a>");b.push("</li>")}),a.html(['<div class="thd"><h3 class="clearfix"><a target="_blank" href="http://2000.bbs.tianya.cn/djmanage/djpage.asp?djid=12385">更多</a></h3></div><ul class="clearfix">',
b.join(""),"</ul>"].join("")),jQuery("#spaceBrandAd").show())}})};
TUI.clickArticle=function(a){var c=a(".js-bbs-act"),b=bbsGlobal.item,d=decodeURIComponent(c.attr("js_blockname")),e=bbsGlobal.artId,g=decodeURIComponent(c.attr("js_title")),c=decodeURIComponent(c.attr("js_activityusername")),h=parseInt(__global.getUserId());0<h||(h=336604);var b=b.toLowerCase(),f={},f=!0==__global.isOnline()?{item:b,itemName:d,idArticle:e,title:g,writer:c,userId:h}:{item:b,idArticle:e};a.getScript("http://click.tianyaui.com/clkme.jsp?"+a.param(f))};
TUI.listenKeyBoardPrevNext=function(a){a(document).keydown(function(c){var b=a(c.target).prop("tagName");"INPUT"===b||"TEXTAREA"===b||(c=c.which,b=null,37===c&&(b=a(".js-keyboard-prev").attr("href")),39===c&&(b=a(".js-keyboard-next").attr("href")),b&&(window.location.href=b))})};
TUI.setFolatMenu=function(a){a("body").append('<div id="flat_menu" class="bbs-flat-menu"><div class="scroll-btn"><a href="javascript:scroll(0, 0);" class="s-btn scroll-top-btn js-scroll-top-btn"></a><a href="#fabu_anchor" class="s-btn toreply-btn js-toreply-btn"></a></div></div>');var c=a("#flat_menu"),b=a("#doc"),d=0,e=0,g=0,h=a.browser.msie&&"6.0"===a.browser.version?!0:!1,f=h?"absolute":"fixed",i=function(){d=a(window).width();e=b.outerWidth();g=c.outerWidth();dScrollTopHeight=c.outerHeight();
var j=Math.max(a(document).height()-b.offset().top-b.outerHeight()-30,0);d>e+2*g?c.css({left:(d+e)/2,right:"auto"}):c.css({left:"auto",right:0});h?c.css({top:a(document).scrollTop()+a(window).height()-j-dScrollTopHeight,bottom:"auto",position:f}).show():c.css({top:"auto",position:f}).show()};a("a.js-toreply-btn").bind("click",replyTop);var k=null;h?a(window).bind("resize scroll",function(){c.hide();clearTimeout(k);k=setTimeout(function(){i()},300)}):a(window).bind("resize",function(){i()});i()};
TUI.getJS=function(a){a.getScript("http://static.tianyaui.com/global/wizard/js/wizard.js")};
TUI.initFontSet=function(){function a(){c(".bbs-content").css({"font-size":e.size+"px","font-family":2===+e.family?"微软雅黑":"宋体","padding-left":e.padding,"padding-right":e.padding});2===+e.family?c(".font-set-view .font-family").addClass("font-family-2"):c(".font-set-view .font-family").removeClass("font-family-2");c(".btn-color").removeClass("btn-color-sel");c("body").removeClass("bg-1 bg-2 bg-3 bg-4 bg-5");e.bgColor&&(c(".btn-color").eq(e.bgColor-1).addClass("btn-color-sel"),c("body").addClass("bg-"+
e.bgColor));TY.io.storage.set(b,e)}var c=jQuery,b="bbs_font",d=function(){this.size=16;this.padding=0;this.bgColor=this.family=1},e=new d;TY.io.storage.get(b)&&""!=TY.io.storage.get(b)&&(c.extend(e,TY.io.storage.get("bbs_font")),a());var g=c("#font_set"),h=c(".font-set-view");c(document).bind("click",function(a){a=c(a.target);0==a.closest(h).size()&&a.prop("id")!=g.attr("id")&&(h.hide(),g.attr("_open",0))});g.bind("click",function(){var a=c(this);"undefined"==typeof a.attr("_open")||0==a.attr("_open")?
(a.attr("_open",1),h.show()):(h.hide(),a.attr("_open",0))});c(".font-size-add",h).bind("click",function(){64!=e.size&&(e.size+=2,64<e.size&&(e.size=64),a())});c(".font-size-red",h).bind("click",function(){12!=e.size&&(e.size-=2,12>e.size&&(e.size=12),a())});c(".font-family",h).bind("click",function(){e.family=1===e.family?2:1;a()});c(".padding-add",h).bind("click",function(){120!=e.padding&&(e.padding+=10,120<e.padding&&(e.padding=120),a())});c(".padding-red",h).bind("click",function(){0!=e.padding&&
(e.padding-=10,0>e.padding&&(e.padding=0),a())});c(".btn-color",h).bind("click",function(){var b=+c(this).attr("_value");b!=e.bgColor&&(e.bgColor=b,a())});c(".btn-reset",h).bind("click",function(){e=new d;a();TY.io.storage.remove(b)})};
TUI.checkVipStatus=function(a){var c=a(".js-vip-check");if(0!==c.size()){var b={},d="";c.each(function(){d=a(this).attr("uid");isNaN(+d)||(b[d]||(b[d]=[]),b[d].push(a(this)))});var e=[];a.each(b,function(a){e.push(a)});if(0!==e.length){var g=function(a){var b=0;2==a.type&&(b=3);1==a.type&&(b=2);3==a.type&&(b=1);return b},h=function(b,c){var d=g(c);if(3!=d){var e=TUI.getVipCode(d);a.each(b,function(){a(this).after(e)})}},c="http://806.tianya.cn/adsp/user/getVIipUser.jsp?userid="+e.join(",");a.ajax({url:c,
dataType:"jsonp",jsonp:"jsonpcallback",success:function(c){if(c&&0!==c.length){var d="",e=[];a.each(c,function(a,c){d=c.userId;e=b[d]||[];h(e,c)})}}})}}};
TUI.userNameRelated=function(){function a(a,c,d,f){c='<div id="person_info_detail" class="none" ><div class="person_arrow"></div>'+('<div class="fl"><p class="imgArea"><img src="http://tx.tianyaui.com/logo/'+a+'" width="50" height="50"/></p><div class="focus-btn"><a _data="'+a+'" class="t-setfocus t-notfocus" href="javascript:void(0);"></a></div></div>')+'<div class="fl ml10"><ul>';c=b(".js-bbs-act").attr("js_activityuserid")===a?c+('<li class="see_ico'+(see_only_uname?" none":"")+'"><a href="javascript:void(0)" class="see_hostone" _host="'+
f+'" _stat="/stat/bbs/post/只看楼主浮层">只看楼主</a></li>'):c+('<li class="see_ico'+(see_only_uname?" none":"")+'"><a href="javascript:void(0)" class="see_soneone" _host="'+f+'" pid="'+d+'" _stat="/stat/bbs/post/只看此人浮层">只看此人</a></li>');c+='<li class="see_ico'+(see_only_uname?"":" none")+'"><a href="javascript:void(0)" class="see_all">查看全部</a></li>';return c+'<li class="email_ico"><a href="javascript:void(0)" class="msgSend">发短信息</a></li>'+('<li class="msg_ico"><a href="http://www.tianya.cn/'+a+'/bbs" target="_blank">TA的帖子</a></li>')+
('<li class="pic_ico"><a href="http://www.tianya.cn/'+a+'/album" target="_blank">TA的相册</a></li>')+"</ul></div></div>"}function c(){b("#person_info_detail").remove();b(document).unbind("click.person_info");clearTimeout(d)}var b=jQuery,d;b(".js-vip-check").livequery("mouseenter",function(){clearTimeout(d);0<b("#person_info_detail").size()&&b("#person_info_detail").remove();var e=b(this).offset(),g=b(this).attr("uid"),h=b(this).attr("uname"),f=b(this).closest(".atl-item").attr("_host"),i=b(this).closest(".atl-item").attr("id")||
"post_head",k=b(".js-bbs-act").attr("js_activityusername");b("body").append(a(g,h,i,k));b("#person_info_detail").attr("uid",g);b("#person_info_detail").css({top:e.top+22,left:e.left-56}).show(0);b(".msgSend",b("#person_info_detail")).bind("click",function(){TY.loader("TY.ui.sendMsg",function(){new TY.ui.sendMsg({recUname:h})})});b(".see_hostone",b("#person_info_detail")).bind("click",function(){var a=b(this).attr("_host");see_only_uname?see_only_uname!=a?(b(".atl-item[_host='"+a+"']").show(),setOnlyUser(a)):
cancelOnlyUser():setOnlyUser(a);b(this).parent().hide();b(this).parent().next().show()});b(".see_soneone",b("#person_info_detail")).bind("click",function(){var a=i||"";see_only_uname?cancelOnlyUser(a):setOnlyUser(f,a);b(this).parent().hide();b(this).parent().next().show()});b(".see_all",b("#person_info_detail")).bind("click",function(){cancelOnlyUser(i);b(this).parent().hide();b(this).parent().prev().show();b(".bbs-info-hint").remove()});b("#person_info_detail").livequery("mouseout",function(){d=
setTimeout(function(){c()},1E3)}).livequery("mouseover",function(){clearTimeout(d)});b(document).bind("click.person_info",function(a){0<b("#person_info_detail").size()?(a=a.target,!b.contains(b("#person_info_detail").get(0),a)&&b("#person_info_detail").get(0)!=a&&c()):c()})}).livequery("mouseleave",function(){d=setTimeout(function(){c()},1E3)})};var _gaq=_gaq||[],_hmt=_hmt||[];
TUI.statistics=function(a){a.getScript("http://click.tianyaui.com/b.jsp?user="+encodeURIComponent(__global._isOnline?__global.getUserName():""));a.ajax({url:"http://static.tianyaui.com/global/ty/stat/stat_20080313.js",dataType:"script",type:"get",scriptCharset:"gbk",success:function(){}});a.ajax({url:"http://hm.baidu.com/h.js?bc5755e0609123f78d0e816bf7dee255",cache:!0,dataType:"script",type:"get",success:function(){var a=TY.param.getParam("event");a&&(a=a.split("|"),2==a.length&&_hmt.push(["_trackEvent",
a[1],a[0],"",""]))}})};
TUI.initBlockSearch=function(a){function c(a){k&&k.abort();k=d.ajax({url:"http://bbs.tianya.cn/api?method=bbs.ice.itemSearch",data:{"params.bOnlyReadWei":!i,"params.key":a},dataType:"json",success:function(c){if(1==c.code&&1==c.success&&c.data&&c.data.rows&&0<c.data.rows.length){var c=c.data.rows,e=[];html="";for(var f=0;f<c.length&&8>f;f++)e=c[f].split("/"),html+='<li><a href="http://bbs.tianya.cn/list-'+e[0]+'-1.shtml">'+e[1].toLowerCase().replace(a,"<strong>"+a+"</strong>")+"</a></li>";h.html(d("<ul></ul>").html(html)).show()}else b()}})}
function b(){k&&k.abort();h.html("").hide()}var d=jQuery,e=d("input#a_btn"),a=a.find("form"),g=d("input:#s_key"),h=d('<div id="laiba_search_result"></div>').appendTo("body"),f="",i=g.hasClass("searchAll"),k=null;g.size()&&(h.css({width:g.width()+10,top:g.offset().top+32,left:g.offset().left}),d(window).bind("resize",function(){var a=g.offset();h.css({top:a.top+32,left:a.left})}));e.bind("click",function(){__global.isOnline()?d.getJSON("/api?"+d.param({method:"bbs.api.isUserCanCreateItem","params.userId":__global.getUserId(),
"params.userName":__global.getUserName()}),function(a){a&&"1"==a.code&&"1"==a.success&&("true"===a.data.isAllow?location="http://bbs.tianya.cn/index_self_apply.jsp":TY_Common_util.showTips("warn",a.data.info))}):TY.loginAction()});a.bind("submit",function(){if(""==d.trim(g.val()))return!1});g.bind("keyup",function(a){if(38===a.which||40===a.which){var e=h.find("li").size();if(e){var i=h.find("li.on").index();38===a.which?(0>i&&(i=e),i--):(0>i&&(i=-1),i++);h.find("li").removeClass("on").eq(i%e).addClass("on");
a=h.find("li.on a").text();g.val(a);f=a}}else a=d.trim(d(this).val()).toLowerCase(),""!==a&&a!==f?(f=a,c(a)):""===a&&(b(),f="")}).bind("blur",function(){setTimeout(function(){b()},100)});h.delegate("li","mouseenter",function(){d(this).addClass("on").siblings().removeClass("on")}).delegate("li","mouseleave",function(){d(this).removeClass("on")})};
TUI.initDashang=function(a){var c=jQuery,b=bbsGlobal.dashang||{};a.bind("click",function(){__global.isOnline()?TY.loader("TY.ui.dashang",function(){TY.ui.dashang.init({src:"http://shang.tianya.cn/order/index.do?merId="+b.merId+"&merNum="+b.merNum+"&getName="+b.getName+"&time="+b.time+"&ext1="+b.ext1+"&ext2="+b.ext2+"&sign="+b.sign})}):TY.loginAction()});c(".host-dashang-btn").size()&&(c(".host-dashang-btn").bind("click",function(){a.triggerHandler("click")}),c(".host-dashang").size()&&isIE6&&795<
c(".host-dashang").width()&&c(".host-dashang").width(795));c(".dashang-btn").size()&&c(".dashang-btn").bind("click",function(){a.triggerHandler("click")})};TUI.initBbsAudio=function(a){a.bind("click",function(){new TY.ui.pop({headTxt:"播放语音",type:"alert",body:'<div id="downloadAppPop"><p>　　您好，目前语音功能只能在手机客户端使用，如果您手机还没安装客户端，可以用以下方式下载安装。</p><p>　　1、手机扫描二维码下载<br>　　<img src="http://static.tianyaui.com/global/lite/images/audioApp2Dcode.png" alt="天涯社区" /></p><p>　　2、<a href="http://itunes.apple.com/cn/app/tian-ya-she-qu/id529696004?mt=8">电脑下载（iPhone版）</a></p><br><p>　　3、<a href="http://www.tianya.cn/mobile/client/tianya-android.apk">电脑下载（Android版）</a></p></div>'})})};
function BasicFun(){TUI.ifMod("#laiba_search",TUI.initBlockSearch);TUI.run(TUI.initAdmin);TUI.run(TUI.formatBbsMusic);resetDom.init();TUI.ifMod("#font_set",TUI.initFontSet);TUI.run(TUI.initReport);TUI.run(TUI.initMark);TUI.run(TUI.initPostView);TUI.run(TUI.listenKeyBoardPrevNext);TUI.run(TUI.initTopMore);TUI.run(TUI.initShareBox);TUI.ifMod("#dashang_btn",TUI.initDashang);TUI.ifMod(".bbs-audio-wrap",TUI.initBbsAudio)}
if("undefined"!=typeof bbsGlobal.itemPermission&&4==bbsGlobal.itemPermission&&!__global._isOnline)TY.loginAction(!1);else{var isIE6=jQuery.browser.msie&&6==jQuery.browser.version?!0:!1;isIE6||BasicFun();jQuery(document).ready(function(a){isIE6&&BasicFun();__global.isOnline()&&"y"==__global.getPartCookie("right","web4")&&jQuery(".facebiz").css("display","inline-block");TUI.run(TUI.checkVipStatus);TUI.run(TUI.userNameRelated);TUI.run(TUI.setFolatMenu);TUI.run(TUI.relevantAct_web);TUI.ifMod("#relevant_article",
TUI.relevantAct);TUI.ifMod("#SpaceBrand",TUI.initBrand);TUI.run(TUI.show2DBarcode);__global.isOnline()?a("#author_name_reply").html(bbsGlobal.trueName||__global.getUserName()):a("#author_name_reply").parent().remove();TUI.run(TUI.clickArticle);TUI.run(TUI.getJS);TUI.run(TUI.statistics);a("#ty_msg_mod").livequery(function(){a(this).css("zIndex",1E6)});var c="no11,no04,travel,843,685,798,973,12,131,872,840,243,919,680,no21,687,990,689,769,903,819,688,686,725,739,750,817,818,820,831,832,833,874,881,884,886,909,922,926,928,153,156,159,173,176,178,179,183,186,189,191,194,199,202,203,207,208,212,220,223,224,227,230,231,233,234,235,237,238,244,248,249,250,251,253,254,255,256,257,259,260,261,262,263,264,265,266,267,269,270,272,273,276,277,278,283,284,285,287,290,293,294,296,297,299,300,301,303,304,306,307,308,311,312,314,315,316,317,319,320,322,323,325,326,327,329,331,333,338,339,340,341,342,360,365,385,388,39,391,392,393,40,41,419,42,421,44,449,45,452,454,455,456,457,458,459,46,460,462,463,464,465,466,467,47,488,489,490,491,492,493,5001,5004,5005,5006,5007,5009,5010,5016,5018,5019,5023,5027,5028,5029,5030,5031,5032,5033,5034,5035,5036,5037,5038,5039,5040,5043,5044,5045,5046,5047,5048,5049,5050,5051,5052,5053,5055,5058,5059,506,5060,5061,5062,5063,5064,5065,5066,5068,5069,5070,5072,5075,5076,5078,5082,5085,5086,5087,5089,5090,5091,5092,5093,5094,5095,5096,5097,5098,5099,5100,5101,5102,5103,5104,5106,5107,5108,5109,5110,5111,5112,5113,5114,5115,5120,5121,5122,5123,5124,5125,5127,5128,5129,5130,5131,5132,5133,5135,5137,5138,5139,5140,5141,5142,5143,5144,5146,5147,5148,5150,5153,5154,5155,5156,5157,5158,5159,5160,5161,5162,5163,5164,5165,5166,5167,5168,5169,5170,5171,5172,5173,5174,5175,5176,5177,5178,5179,5180,5181,5182,5183,5184,5185,5186,5187,5188,5189,5190,5191,5192,5193,5194,5195,5197,5198,5199,52,5201,5202,5203,5204,5205,5206,5207,5208,5209,5210,5211,5212,5213,5214,5215,5216,5217,5218,5219,5220,5221,5222,5223,5224,5225,5226,56,58,59,60,62,63,65,670,677,72,726,73,736,754,757,77,78,79,794,80,82,88,89,90,92,937,97,ehomephot,hn,laoba,mfinances,outseachina,schoolculture,servantonline,volunteerhn,xhw,22".split(",");
"undefined"!=typeof c&&0<c.length&&bbsGlobal.item&&0<c.indexOf(bbsGlobal.item)&&a.getScript(TY_lite_url+"/js/bbs/highlight.js");a(".addpost").livequery("click",function(a){!__global.isOnline()&&!1===LaboratoryTest()&&(TY.loginAction(),a.preventDefault())})})};
